### ISSUE TITLE
Rename the virtualHost.tls settings

### ISSUE THREAD

**Issue by dieti80** [libuweber/microgateway#21]
Rename the virtualHost.tls settings as follow:

Currently:
```
    virtualHost:
      tlsCipher:
        enabled: false
        protocol: ""
        cipherSuite: ""
```

New:
```
    virtualHost:
      tls:
        enabled: false
        protocol: ""
        cipherSuite: ""
```

https://github.com/libuweber/microgateway/blob/ee2c71ea91b5a02b6d418df5fcd0b30bffed2cd9/charts/microgateway/values.yaml#L52

We do have the same structure for backend.tls.enabled, backend.tls.protocol, backend.tls.cipherSuite.
